env:
  - APPID=""
  
jobs:
 include:
  - stage: "Deploy"
    name: "Build and deploy"
    before_script: echo $APPID
    script: APPID="abc-123-def"
    after_script: echo $APPID
  - stage: "Test"
    name: "Testing"
    script: echo $APPID