jobs:
 includes:
  - stage: "Build App and Deploy"
    script: echo "Uploading new version to github"
  - stage: "Test"
    language: node_js
    node_js: "nodejs"
    name: "Test with Kobiton"
    script: abc.sh