# script: echo "Build"
#   #Build project

# deploy: echo "Deploy"
#   #Upload app to HockeyApp

# after_deploy: echo "After deploy"
#   #Store App ID

# after_script: echo "Test"
#   #Start testing

jobs:
 include:
  - stage: "Deploy"
    name: "Build and deploy"
    script: echo ‘export var=x’ >> $BASH_ENV
  - stage: "Test"
    name: "Testing"
    script: echo $var